### ISSUE TITLE
手数が不明な詰みを発見した場合のコマンドでParseErrorが出る

### ISSUE THREAD

**Issue by SakodaShintaro** [yaneurao/Ayane#6]
将棋所(http://shogidokoro.starfree.jp/usi.html) は
> ただし、「詰みを発見したが、手数がわからない」ということがあるかもしれません。（実は、サンプル用のエンジンであるLesserkaiが詰みを発見したときがこの状況になります。）こういう場合は、score mate + またはscore mate - のように、数字を使わず、単に+または-の記号を使用するようにして下さい。（これはUSIの原案にはありませんが、将棋所で機能追加しています。）

ということで"score mate +"のような出力を許していて、それに合わせて技巧が入玉のときに
>  info depth 1 nodes 0 time 0 score mate + string Nyugyoku

という出力をするのですがこれがParseErrorになってしまいます（intを期待して+が来てしまうので）。おそらく対局に影響はないのでどうでもいいっちゃどうでもいいんですが一応報告しておきます。

**Comment by yaneurao** [comment]
https://github.com/yaneurao/Ayane/commit/d314546965d87d84f3fb6b9e28b4eae69fc248bc
で修正してみましたが、技巧でテストしてないのでこれでうまく修正できているかどうかわかりません(´ω｀)　何かあればまた教えていただければと…。
